on:
  push:
    branches: ['v3-alpha']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'v3-alpha'
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.29.1

      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: |
          npm ci
          npm run build:types
          npm run build:docs
        working-directory: v3/internal/runtime/desktop/@wailsio/runtime

      - name: test action
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3.2
        with:
          path: v3/internal/runtime/desktop/@wailsio/runtime

      - name: Print the version
        run: echo "The version was ${{ steps.get-version.outputs.version }}"
      - name: Commit changes
        run: |
          git add .
          git commit -m "chore: Publish @wailsio/runtime ${{ steps.get-version.outputs.version }}"
          git push

      - uses: JS-DevTools/npm-publish@v3
        with:
          package: v3/internal/runtime/desktop/@wailsio/runtime
          access: public
          token: ${{ secrets.NPM_TOKEN }}