on:
  push:
    branches: ['v3-alpha']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'v3-alpha'
          ssh-key: ${{ secrets.DEPLOY_KEY }}


      - name: Configure git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Test+Build
        run: |
          npm ci
          npm test
          npm run build
        working-directory: v3/internal/runtime/desktop/@wailsio/runtime

      - name: Build bundled runtime
        run: |
          npx --yes -p esbuild@latest exit
          task runtime:build
        working-directory: v3

      - name: Detect build artifact changes
        uses: tj-actions/verify-changed-files@v20
        id: build-artifact-changes
        with:
          files: v3/internal/runtime/desktop/@wailsio/runtime/{dist,types,docs}/**

      - name: Bump version
        if: steps.build-artifact-changes.outputs.files_changed == 'true'
        run: |
          npm version prerelease
        working-directory: v3/internal/runtime/desktop/@wailsio/runtime

      - name: Get version
        if: steps.build-artifact-changes.outputs.files_changed == 'true'
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3.2
        with:
          path: v3/internal/runtime/desktop/@wailsio/runtime

      - name: Commit changes
        if: steps.build-artifact-changes.outputs.files_changed == 'true'
        run: |
          git add .
          git commit -m "[skip ci] Publish @wailsio/runtime ${{ steps.get-version.outputs.version }}"
          git push

      - uses: JS-DevTools/npm-publish@v3
        if: steps.build-artifact-changes.outputs.files_changed == 'true'
        with:
          package: v3/internal/runtime/desktop/@wailsio/runtime
          access: public
          token: ${{ secrets.NPM_TOKEN }}

      - name: Detect bundled runtime changes
        if: steps.build-artifact-changes.outputs.files_changed != 'true'
        uses: tj-actions/verify-changed-files@v20
        id: bundle-changes
        with:
          files: v3/internal/assetserver/bundledassets/**

      - name: Commit bundled runtime changes
        if: steps.build-artifact-changes.outputs.files_changed != 'true' && steps.bundle-changes.outputs.files_changed == 'true'
        run: |
          git add .
          git commit -m "[skip ci] Update bundled runtime"
          git push
