name: V3 Changelog Validator

on:
  pull_request:
    branches: [ v3-alpha ]
    paths:
      - 'docs/src/content/docs/changelog.mdx'
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to check (for manual testing)'
        required: false
        type: string

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event.inputs.pr_number
    
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Test simple workflow
      run: |
        echo "Testing workflow - PR number: ${{ github.event.inputs.pr_number || github.event.pull_request.number }}"
        echo "This workflow validates changelog entries"
        
    - name: Comment on PR
      if: github.event.inputs.pr_number
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.createComment({
            issue_number: ${{ github.event.inputs.pr_number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Test comment from simplified workflow'
          });